# Generated by Django 3.2.8 on 2021-10-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('sub_titulo', models.CharField(max_length=350)),
                ('info', models.TextField()),
                ('categoria', models.CharField(choices=[('DT', 'Destaque'), ('PA', 'Padrao'), ('SE', 'Semanal')], max_length=15)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
