# Generated by Django 3.2.8 on 2021-11-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='foto'),
        ),
    ]
